-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `role` ENUM('admin', 'employee') NOT NULL DEFAULT 'employee',

    UNIQUE INDEX `User_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Applicant` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `applicantName` VARCHAR(191) NOT NULL,
    `dob` VARCHAR(191) NOT NULL,
    `education` VARCHAR(191) NOT NULL,
    `panCard` VARCHAR(191) NOT NULL,
    `gender` VARCHAR(191) NOT NULL,
    `mobile` VARCHAR(191) NOT NULL,
    `address` VARCHAR(191) NOT NULL,
    `block` VARCHAR(191) NOT NULL,
    `fatherOrHusband` VARCHAR(191) NOT NULL,
    `mother` VARCHAR(191) NOT NULL,
    `panchayat` VARCHAR(191) NOT NULL,
    `familyIncome` VARCHAR(191) NOT NULL,
    `bankAccount` VARCHAR(191) NOT NULL,
    `ifsc` VARCHAR(191) NOT NULL,
    `sanctionYear` VARCHAR(191) NOT NULL,
    `disbursementYear` VARCHAR(191) NOT NULL,
    `village` VARCHAR(191) NOT NULL,
    `aadhar` VARCHAR(191) NOT NULL,
    `residentialCert` VARCHAR(191) NOT NULL,
    `casteCert` VARCHAR(191) NOT NULL,
    `incomeCert` VARCHAR(191) NOT NULL,
    `category` VARCHAR(191) NOT NULL,
    `loanType` VARCHAR(191) NOT NULL,
    `businessName` VARCHAR(191) NOT NULL,
    `shopName` VARCHAR(191) NOT NULL,
    `guarantorName` VARCHAR(191) NOT NULL,
    `guarantorFather` VARCHAR(191) NOT NULL,
    `guarantorAddress` VARCHAR(191) NOT NULL,
    `guarantorOffice` VARCHAR(191) NOT NULL,
    `guarantorOccupation` VARCHAR(191) NOT NULL,
    `guarantorEmployerType` VARCHAR(191) NOT NULL,
    `guarantorDesignation` VARCHAR(191) NOT NULL,
    `guarantorMobile` VARCHAR(191) NOT NULL,
    `guarantorAadhar` VARCHAR(191) NOT NULL,
    `guarantorAffidavit` VARCHAR(191) NOT NULL,
    `marginAmountDraft` VARCHAR(191) NOT NULL,
    `corporation` VARCHAR(191) NOT NULL,
    `sanctionLetterNo` VARCHAR(191) NOT NULL,
    `serialNoCorporation` VARCHAR(191) NOT NULL,
    `sanctionAmount` VARCHAR(191) NOT NULL,
    `disbursementAmount` VARCHAR(191) NOT NULL,
    `firstChequeNo` VARCHAR(191) NOT NULL,
    `firstChequeDate` VARCHAR(191) NOT NULL,
    `secondChequeNo` VARCHAR(191) NOT NULL,
    `secondChequeDate` VARCHAR(191) NOT NULL,
    `dwoPaymentOrderNo` VARCHAR(191) NOT NULL,
    `firstInstallmentChequeNo` VARCHAR(191) NOT NULL,
    `secondInstallmentChequeNo` VARCHAR(191) NOT NULL,
    `subsidyStatus` VARCHAR(191) NOT NULL,
    `emiAmount` VARCHAR(191) NOT NULL,
    `emiDate` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
